import './site-home.css';

export default function SiteHome(){return <main className="site-home">
 <header><a className="site-home-brand" href="/"><span>S</span><b>SITIOWEB.SHOP</b></a><nav><a href="#servicio">Servicio</a><a href="#proceso">Cómo funciona</a><a href="https://estudiocontableforchlau.sitioweb.shop" target="_blank">Ver ejemplo</a></nav><a className="site-home-admin" href="https://creador.sitioweb.shop">Administrar</a></header>
 <section className="site-home-hero"><div><small>SITIOS PREMIUM CON PANEL EDITABLE</small><h1>Tu negocio merece una web que venda.</h1><p>Creamos páginas rápidas, profesionales y listas para compartir. Cada cliente recibe su propio subdominio y un panel para editar textos, imágenes e información.</p><div><a href="https://estudiocontableforchlau.sitioweb.shop" target="_blank">Ver sitio de muestra <b>↗</b></a><a href="#servicio">Conocer el servicio</a></div></div><aside><span>PRIMER SITIO</span><strong>estudiocontableforchlau</strong><small>.sitioweb.shop</small><ul><li>Diseño adaptable</li><li>Panel administrador</li><li>Dominio seguro</li><li>Carga optimizada</li></ul></aside></section>
 <section id="servicio" className="site-home-features"><article><b>01</b><h2>Identidad propia</h2><p>Diseño, colores, logo, fotografías y textos alineados con cada empresa.</p></article><article><b>02</b><h2>Edición sencilla</h2><p>El cliente administra su contenido sin tocar código ni depender de terceros.</p></article><article><b>03</b><h2>Subdominio incluido</h2><p>Una dirección profesional como <strong>empresa.sitioweb.shop</strong>, lista para vender.</p></article></section>
 <section id="proceso" className="site-home-process"><small>UN PROCESO CLARO</small><h2>De la idea a una web publicada</h2><div><article><span>1</span><b>Elegimos una plantilla</b><p>Partimos del rubro y objetivos del negocio.</p></article><article><span>2</span><b>Personalizamos la marca</b><p>Aplicamos fotos, logo, colores y contenido real.</p></article><article><span>3</span><b>Entregamos el acceso</b><p>El cliente recibe su enlace y panel administrador.</p></article></div></section>
 <footer><b>SITIOWEB.SHOP</b><span>Sitios web editables para negocios que quieren crecer.</span><a href="https://estudiocontableforchlau.sitioweb.shop" target="_blank">Ver el primer sitio →</a></footer>
 </main>}
