"use client";
import { useEffect, useState, type FormEvent } from 'react';
type Client={id:number;slug:string;name:string;templateKey:string;createdAt:string};
const rubros=[['restaurantes','Restaurante'],['comida-rapida','Fast food'],['detalles-romanticos','Detalles'],['ropa','Ropa'],['mujer','Mujer'],['zapatos-mujer','Zapatos'],['perfumeria','Perfumería'],['postres','Postres'],['accesorios','Accesorios']];
function renewal(value:string){const d=new Date(value);if(!Number.isFinite(d.getTime()))return 'Sin fecha';const month=d.getUTCMonth();d.setUTCFullYear(d.getUTCFullYear()+1);if(d.getUTCMonth()!==month)d.setUTCDate(0);return d.toLocaleDateString('es-PE',{timeZone:'UTC'});}
export default function CreatorPanel(){
 const [clients,setClients]=useState<Client[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/tenants',{cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'Inicia sesión nuevamente.':'No se pudo consultar los clientes.');const data=await r.json() as {clients:Client[]};setClients(data.clients);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setMessage('');try{const data=Object.fromEntries(new FormData(form));const r=await fetch('/api/tenants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok){const payload=await r.json() as {error?:string};throw new Error(r.status===409?'Ese subdominio ya existe.':payload.error==='template_not_found'?'Ese rubro todavía no tiene una demo disponible.':r.status===400?'Revisa el subdominio y los campos.':r.status===401?'Inicia sesión nuevamente.':'No se pudo crear. No se ha confirmado ningún alta.');}form.reset();setMessage('Cuenta creada. Comprueba su enlace e inicio de sesión antes de entregarla.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Error de conexión');}finally{setBusy(false);}}
 return <main className="creator-only"><header><h1>Clientes y subdominios</h1><button onClick={async()=>{const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok)location.href='/login';}}>Cerrar sesión</button></header><section><h2>Crear catálogo para un cliente</h2><p>Un rubro, acceso propio y datos separados por cliente.</p><form onSubmit={create}><label>Nombre del negocio<input name="name" required maxLength={80}/></label><label>Subdominio<input name="slug" required pattern="[a-z0-9][a-z0-9-]{1,43}[a-z0-9]" placeholder="cliente" autoCapitalize="none"/><small>.xn--micatlogo-41a.shop</small></label><label>Rubro<select name="templateKey">{rubros.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Correo del administrador<input name="email" type="email" autoComplete="off" required maxLength={254}/></label><label>Contraseña inicial<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/><small>Mínimo 12 caracteres. No se mostrará en enlaces ni en la lista.</small></label><button disabled={busy}>{busy?'Creando…':'Crear cliente y subdominio'}</button></form><p role="status">{message}</p></section><section><h2>Clientes creados</h2>{clients.map(c=><article key={c.id}><h3>{c.name}</h3><p>{c.templateKey} · Creado: {new Date(c.createdAt).toLocaleDateString('es-PE',{timeZone:'UTC'})} · Primera renovación: {renewal(c.createdAt)}</p><a href={'https://'+c.slug+'.xn--micatlogo-41a.shop'} target="_blank" rel="noopener noreferrer">Ver catálogo</a>{' · '}<a href={'https://'+c.slug+'.xn--micatlogo-41a.shop/login'} target="_blank" rel="noopener noreferrer">Acceso del cliente</a></article>)}</section><style>{'.creator-only{min-height:100vh;padding:32px max(20px,calc((100vw - 1000px)/2));background:linear-gradient(125deg,#e0f1ff,#eee5ff);color:#182538;font-family:Arial,sans-serif}.creator-only header{display:flex;gap:20px;align-items:center;justify-content:space-between}.creator-only section{padding:28px;background:#ffffffd9;border-radius:24px;margin:22px 0}.creator-only form{display:grid;gap:18px}.creator-only label{display:grid;gap:8px;font-weight:700}.creator-only input,.creator-only select{box-sizing:border-box;width:100%;padding:14px;border:1px solid #a3b4cc;border-radius:12px;font:inherit}.creator-only button{padding:15px 24px;border:0;border-radius:16px;color:white;background:linear-gradient(90deg,#087ffe,#6b4eff);font-weight:700;cursor:pointer}.creator-only button:disabled{opacity:.6}.creator-only small{font-weight:400}.creator-only article{border-top:1px solid #cbd7e4;padding:16px 0}.creator-only a{color:#234ac4}'} </style></main>;
}
