'use client';
import {useEffect,useState,type FormEvent} from 'react';

type SiteClient={id:number;slug:string;name:string;username?:string;templateKey:string;createdAt:string};
async function payload(response:Response){return (response.headers.get('content-type')||'').includes('application/json')?response.json().catch(()=>null):null}

export default function SiteCreator(){
 const [clients,setClients]=useState<SiteClient[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[passwordClientId,setPasswordClientId]=useState<number|null>(null),[generatedPassword,setGeneratedPassword]=useState('');
 async function load(){const response=await fetch('/api/site-tenants',{cache:'no-store'}),data=await payload(response);if(response.status===401){location.href='/login?next=%2Fadmin';return}if(!response.ok)throw new Error('No se pudo consultar los sitios web.');setClients(data?.clients||[])}
 useEffect(()=>{load().catch(()=>setMessage('No se pudo consultar los sitios web.'))},[]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fields=Object.fromEntries(new FormData(form));fields.slug=String(fields.slug||'').toLowerCase().replace(/[^a-z0-9-]/g,'').replace(/^-+|-+$/g,'');setBusy(true);setMessage('');try{const response=await fetch('/api/site-tenants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(fields)}),data=await payload(response);if(!response.ok)throw new Error(response.status===409?'Ese subdominio ya existe.':response.status===400?'Revisa nombre, subdominio y contraseña (mínimo 12 caracteres).':'No se pudo crear el sitio.');form.reset();setMessage(`Sitio creado. Usuario: ${data?.client?.username||fields.name}`);await load()}catch(error){setMessage(error instanceof Error?error.message:'No se pudo crear el sitio.')}finally{setBusy(false)}}
 async function changePassword(event:FormEvent<HTMLFormElement>,client:SiteClient){event.preventDefault();const form=event.currentTarget,data=new FormData(form),password=String(data.get('password')||''),confirmation=String(data.get('confirmation')||'');if(password!==confirmation){setMessage('Las contraseñas no coinciden.');return}setBusy(true);setMessage('');try{const response=await fetch('/api/site-tenants',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:client.id,slug:client.slug,password})});if(!response.ok)throw new Error('No se pudo cambiar la contraseña.');form.reset();setPasswordClientId(null);setGeneratedPassword('');setMessage(`Contraseña actualizada para ${client.name}.`)}catch(error){setMessage(error instanceof Error?error.message:'No se pudo cambiar la contraseña.')}finally{setBusy(false)}}
 async function remove(client:SiteClient){if(!confirm(`¿Eliminar definitivamente ${client.name}? Esta acción no se puede deshacer.`))return;setBusy(true);setMessage('');try{const response=await fetch('/api/site-tenants',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:client.id,slug:client.slug})});if(!response.ok)throw new Error('No se pudo eliminar el sitio.');setClients(current=>current.filter(item=>item.id!==client.id));setMessage(`${client.name} fue eliminado.`)}catch(error){setMessage(error instanceof Error?error.message:'No se pudo eliminar el sitio.')}finally{setBusy(false)}}
 function generatePassword(event:React.MouseEvent<HTMLButtonElement>){const form=event.currentTarget.closest('form'),passwordInput=form?.querySelector<HTMLInputElement>('input[name="password"]'),confirmationInput=form?.querySelector<HTMLInputElement>('input[name="confirmation"]'),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%',values=crypto.getRandomValues(new Uint32Array(18)),password=Array.from(values,value=>alphabet[value%alphabet.length]).join('');if(passwordInput)passwordInput.value=password;if(confirmationInput)confirmationInput.value=password;setGeneratedPassword(password)}
 return <section className="site-creator">
  <div className="site-creator-heading"><small>SITIOWEB.SHOP</small><h2>Crear landing y subdominio</h2><p>Cada cliente recibe su sitio, contraseña y panel de edición independientes.</p></div>
  <form className="site-create-form" onSubmit={create}><label>Nombre del negocio<input name="name" required maxLength={80} placeholder="Estudio Contable FORCHLU"/></label><label>Subdominio<div className="site-slug"><input name="slug" required minLength={3} maxLength={45} pattern="[A-Za-z0-9][A-Za-z0-9-]{1,43}[A-Za-z0-9]" placeholder="estudiocontableforchlau"/><b>.sitioweb.shop</b></div></label><label>Plantilla<select name="templateKey"><option value="site:accounting">Estudio contable premium</option></select></label><label>Contraseña inicial<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/><small>Mínimo 12 caracteres.</small></label><button disabled={busy}>{busy?'Creando…':'Crear sitio y subdominio'}</button></form>
  <p className="site-message" role="status">{message}</p>
  <div className="site-client-list"><h3>Sitios web creados</h3>{clients.length===0&&<p>Aún no hay sitios creados.</p>}{clients.map(client=><article key={client.id}><div><b>{client.name}</b><span>{client.slug}.sitioweb.shop</span><small>Usuario: {client.username||client.name}</small></div><div className="site-actions"><a href={`https://${client.slug}.sitioweb.shop`} target="_blank">Ver sitio</a><a href={`https://${client.slug}.sitioweb.shop/login?next=%2Fadmin`} target="_blank">Panel del cliente</a><button type="button" disabled={busy} onClick={()=>{setPasswordClientId(passwordClientId===client.id?null:client.id);setGeneratedPassword('')}}>Cambiar contraseña</button><button type="button" className="site-delete" disabled={busy} onClick={()=>remove(client)}>Eliminar</button></div>{passwordClientId===client.id&&<form className="site-password" onSubmit={event=>changePassword(event,client)}><label>Nueva contraseña<input name="password" type="password" minLength={12} maxLength={128} required/></label><label>Confirmar contraseña<input name="confirmation" type="password" minLength={12} maxLength={128} required/></label><button type="button" onClick={generatePassword}>Generar contraseña</button>{generatedPassword&&<code>{generatedPassword}</code>}<button disabled={busy}>Guardar nueva contraseña</button></form>}</article>)}</div>
  <style>{`.site-creator{margin:22px 0;padding:28px;border-radius:24px;background:linear-gradient(145deg,#071426,#101f3b);color:#fff;box-shadow:0 22px 55px #05122630}.site-creator-heading small{color:#78a9ff;font-weight:900;letter-spacing:.16em}.site-creator-heading h2{margin:7px 0;font-size:28px}.site-creator-heading p{margin:0 0 22px;color:#b9c8de}.site-create-form{display:grid;grid-template-columns:1fr 1fr;gap:16px}.site-create-form label,.site-password label{display:grid;gap:7px;font-weight:800}.site-create-form input,.site-create-form select,.site-password input{box-sizing:border-box;width:100%;min-height:48px;padding:0 13px;border:1px solid #456184;border-radius:12px;background:#fff;color:#15243a;font:inherit}.site-slug{display:flex;align-items:center;border-radius:12px;background:#fff;overflow:hidden}.site-slug input{border:0}.site-slug b{padding-right:12px;color:#526780;white-space:nowrap}.site-create-form>button{grid-column:1/-1;min-height:52px;border:0;border-radius:13px;background:linear-gradient(100deg,#d70b19,#2d6cca);color:#fff;font-weight:900}.site-message{min-height:22px;color:#ffd1d6;font-weight:800}.site-client-list{margin-top:24px}.site-client-list article{display:grid;grid-template-columns:minmax(190px,1fr) 2fr;gap:16px;padding:18px 0;border-top:1px solid #ffffff20}.site-client-list article>div:first-child{display:grid;gap:4px}.site-client-list span,.site-client-list small{color:#b7c9e3}.site-actions{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:9px}.site-actions a,.site-actions button,.site-password button{padding:10px 13px;border:0;border-radius:10px;background:#2868c7;color:#fff;text-decoration:none;font-weight:800}.site-actions .site-delete{background:#a81f2a}.site-password{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:16px;border-radius:15px;background:#ffffff10}.site-password code{align-self:center;padding:10px;border-radius:9px;background:#020814;overflow-wrap:anywhere}@media(max-width:720px){.site-create-form,.site-client-list article,.site-password{grid-template-columns:1fr}.site-actions{justify-content:stretch}.site-actions>*{width:100%;text-align:center}.site-slug b{font-size:12px}}`}</style>
 </section>
}
