'use client';
import {useEffect,useRef,useState,type ChangeEvent} from 'react';
import {accountingIconKeys,defaultAccountingLanding,normalizeAccountingLanding,type AccountingLanding,type LandingItem} from '@/lib/accounting-landing';

const iconNames:Record<string,string>={ledger:'Documento',chart:'Gráfico',growth:'Crecimiento',shield:'Escudo',balance:'Balanza',people:'Equipo',briefcase:'Maletín',target:'Objetivo',folder:'Carpeta',calculator:'Calculadora',check:'Check',building:'Empresa'};

function Icon({name}:{name:string}){const common={fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};const paths:Record<string,React.ReactNode>={
 ledger:<><path {...common} d="M6 3h9l3 3v15H6z"/><path {...common} d="M15 3v4h4M9 11h6M9 15h6"/></>,
 chart:<><path {...common} d="M4 20V9M10 20V4M16 20v-7M22 20H2"/></>,
 growth:<><path {...common} d="m3 17 6-6 4 4 8-9"/><path {...common} d="M16 6h5v5"/></>,
 shield:<><path {...common} d="M12 3 4.5 6v5.5c0 4.7 3.1 7.8 7.5 9.5 4.4-1.7 7.5-4.8 7.5-9.5V6z"/><path {...common} d="m9 12 2 2 4-5"/></>,
 balance:<><path {...common} d="M12 3v18M5 6h14M7 6l-4 8h8zM17 6l-4 8h8z"/></>,
 people:<><path {...common} d="M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a4 4 0 1 0 0-8M18 8a3 3 0 0 1 0 6M22 20v-2a4 4 0 0 0-3-3.7"/></>,
 briefcase:<><path {...common} d="M4 7h16v13H4zM9 7V4h6v3M4 12h16M10 12v2h4v-2"/></>,
 target:<><circle {...common} cx="12" cy="12" r="9"/><circle {...common} cx="12" cy="12" r="5"/><circle {...common} cx="12" cy="12" r="1"/></>,
 folder:<><path {...common} d="M3 6h7l2 2h9v11H3z"/></>,
 calculator:<><rect {...common} x="5" y="2" width="14" height="20" rx="2"/><path {...common} d="M8 6h8v4H8zM8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01M16 18h.01"/></>,
 check:<><circle {...common} cx="12" cy="12" r="9"/><path {...common} d="m8 12 3 3 5-6"/></>,
 building:<><path {...common} d="M4 21V5l8-3 8 3v16M8 8h.01M12 8h.01M16 8h.01M8 12h.01M12 12h.01M16 12h.01M9 21v-5h6v5"/></>
};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]||paths.ledger}</svg>}

function wa(content:AccountingLanding,text:string){return `https://api.whatsapp.com/send?phone=${content.whatsapp.replace(/\D/g,'')}&text=${encodeURIComponent(text)}`}
function BrandLogo({content}:{content:AccountingLanding}){return <img className="accounting-logo" src={content.logoImage} alt={`Logo de ${content.brand}`}/>}
function ClientMarquee({logos,preview=false}:{logos:string[];preview?:boolean}){if(!logos.length)return preview?<section className="client-marquee client-marquee-empty"><p>EMPRESAS QUE CONFÍAN EN NOSOTROS</p><div><b>La marquesina aparecerá aquí</b><span>Sube los logos desde la sección “Clientes”.</span></div></section>:null;const repeated=Array.from({length:Math.max(6,logos.length)},(_,index)=>logos[index%logos.length]);return <section className="client-marquee" aria-label="Clientes que confían en nosotros"><p>EMPRESAS QUE CONFÍAN EN NOSOTROS</p><div className="client-marquee-track">{[0,1].map(copy=><div key={copy} aria-hidden={copy===1}>{repeated.map((logo,index)=><span key={`${copy}-${index}`}><img src={logo} alt={copy?'':`Logo de cliente ${(index%logos.length)+1}`}/></span>)}</div>)}</div></section>}

export function LandingView({content,preview=false}:{content:AccountingLanding;preview?:boolean}){
 const landingRef=useRef<HTMLElement>(null);
 useEffect(()=>{
  const root=landingRef.current;
  if(!root||preview||!('IntersectionObserver' in window))return;
  const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
  if(motion.matches)return;
  const elements=Array.from(root.querySelectorAll<HTMLElement>('.accounting-hero>div>span,.accounting-hero h1,.accounting-hero p,.accounting-hero>div>a,.accounting-copy>small,.accounting-copy>h2,.accounting-copy>p,.section-heading>small,.section-heading>h2,.section-heading>p,.accounting-pillars article>div,.approach-list article>div,.accounting-services article>div,.reason-grid article>div,.accounting-cta>h2,.accounting-cta>p,.accounting-footer>div'));
  const observer=new IntersectionObserver(entries=>{
   entries.forEach(entry=>{
    if(entry.isIntersecting){entry.target.classList.add('text-revealed');observer.unobserve(entry.target)}
   });
  },{threshold:0.08,rootMargin:'0px 0px -24px 0px'});
  elements.forEach(element=>{
   const siblings=elements.filter(item=>item.parentElement===element.parentElement);
   const delay=Math.min(siblings.indexOf(element),3)*140+(element.closest('.accounting-hero')?220:0);
   element.style.setProperty('--reveal-delay',`${delay}ms`);
   element.classList.add('text-reveal');observer.observe(element);
  });
  const showAll=()=>{if(motion.matches){observer.disconnect();elements.forEach(element=>element.classList.add('text-revealed'))}};
  motion.addEventListener('change',showAll);
  return ()=>{observer.disconnect();motion.removeEventListener('change',showAll);elements.forEach(element=>{element.classList.remove('text-reveal','text-revealed');element.style.removeProperty('--reveal-delay')})};
 },[preview]);
 return <main ref={landingRef} className={`accounting-landing${preview?' is-preview':''}`}>
 <div className="accounting-notice"><span>{content.topNotice}</span><a href={wa(content,'Hola, deseo recibir información sobre sus servicios contables.')} target="_blank" rel="noreferrer">{content.brochureLabel} <b>→</b></a></div>
 <header className="accounting-nav"><a className="accounting-brand" href="#inicio"><BrandLogo content={content}/></a><nav><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#beneficios">Beneficios</a><a href="#contacto">Contacto</a></nav><a className="nav-cta" href={wa(content,'Hola, deseo agendar una consulta contable.')} target="_blank" rel="noreferrer">CONSULTA GRATIS</a>{!preview&&<a className="landing-admin-link" href="/estudio-contable/admin">Administrar</a>}</header>
 <section id="inicio" className="accounting-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(3,6,12,.98),rgba(8,26,58,.82) 55%,rgba(186,4,17,.24)),url(${content.heroImage})`}}><div className="accounting-hero-copy"><span>{content.heroEyebrow}</span><h1 className={content.heroTextEffect==='dia'?'dia-text-title':''}>{content.heroTitle}</h1><p>{content.heroDescription}</p><a href={wa(content,'Hola, deseo agendar una consulta para mi empresa.')} target="_blank" rel="noreferrer">{content.heroButton} <b>→</b></a></div><section className="accounting-pillars">{content.pillars.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><b>{item.title}</b><span>{item.description}</span></div></article>)}</section></section>
 <section id="nosotros" className="accounting-split about-block"><div className="accounting-copy"><small>NOSOTROS</small><h2>{content.aboutTitle}</h2><p>{content.aboutText}</p><div className="experience"><strong>{content.experienceValue}</strong><span>{content.experienceLabel}</span></div></div><img src={content.aboutImage} alt="Equipo del estudio contable" loading="lazy"/></section>
 <section className="accounting-split approach-block"><img src={content.approachImage} alt="Asesoría empresarial" loading="lazy"/><div className="accounting-copy"><small>NUESTRA MIRADA</small><h2>{content.approachTitle}</h2><p>{content.approachText}</p><div className="approach-list">{content.approachPoints.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><b>{item.title}</b><span>{item.description}</span></div></article>)}</div></div></section>
 <section id="servicios" className="accounting-services"><div className="section-heading"><small>SERVICIOS</small><h2>{content.servicesTitle}</h2><p>{content.servicesIntro}</p></div><div>{content.services.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><h3>{item.title}</h3><p>{item.description}</p><a href={wa(content,`Hola, deseo información sobre ${item.title}.`)} target="_blank" rel="noreferrer">MÁS INFORMACIÓN <b>→</b></a></div></article>)}</div></section>
 <section id="beneficios" className="accounting-why"><div className="accounting-copy"><small>NUESTRO COMPROMISO</small><h2>{content.whyTitle}</h2><p>{content.whyText}</p><div className="reason-grid">{content.reasons.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><b>{item.title}</b><span>{item.description}</span></div></article>)}</div></div><img src={content.whyImage} alt="Consultoría contable personalizada" loading="lazy"/></section>
 <section className="accounting-cta" style={{backgroundImage:`linear-gradient(90deg,rgba(3,6,12,.97),rgba(9,37,82,.78),rgba(173,4,16,.5)),url(${content.ctaImage})`}}><h2>{content.ctaTitle}</h2><p>{content.ctaText}</p><a href={wa(content,'Hola, deseo solicitar una asesoría contable.')} target="_blank" rel="noreferrer">{content.ctaButton} <b>→</b></a></section>
 <ClientMarquee logos={content.clientLogos} preview={preview}/>
 <footer id="contacto" className="accounting-footer"><a className="accounting-brand" href="#inicio"><BrandLogo content={content}/></a><div><b>CONTACTO</b><span>{content.address}</span><a href={`tel:${content.phone.replace(/[^\d+]/g,'')}`}>{content.phone}</a><a href={`mailto:${content.email}`}>{content.email}</a></div><div><b>SERVICIOS</b>{content.services.slice(0,4).map((item,index)=><span key={index}>{item.title}</span>)}</div></footer>
 </main>}

async function optimize(file:File){if(!file.type.startsWith('image/'))return file;try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')?.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/webp',.82));return blob?new File([blob],file.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'}):file}catch{return file}}

function TextField({label,value,onChange,area=false}:{label:string;value:string;onChange:(value:string)=>void;area?:boolean}){return <label><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function PhotoField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){const [busy,setBusy]=useState(false);async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);try{const form=new FormData();form.append('file',await optimize(file));const response=await fetch('/api/upload?template=landing-contable',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error();onChange(data.url)}catch{alert('No se pudo cargar la imagen.')}finally{setBusy(false)}}return <label className="landing-photo-field"><span>{label}</span><img src={value} alt="Vista previa"/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/><small>{busy?'Optimizando y subiendo…':'JPG, PNG o WebP. Se optimiza automáticamente.'}</small></label>}
function ItemEditor({item,onChange}:{item:LandingItem;onChange:(item:LandingItem)=>void}){return <div className="landing-item-editor"><label><span>Icono</span><select value={item.icon} onChange={e=>onChange({...item,icon:e.target.value})}>{accountingIconKeys.map(key=><option key={key} value={key}>{iconNames[key]}</option>)}</select></label><TextField label="Título" value={item.title} onChange={title=>onChange({...item,title})}/><TextField label="Descripción" value={item.description} area onChange={description=>onChange({...item,description})}/></div>}
function LogoEditor({logos,onChange}:{logos:string[];onChange:(logos:string[])=>void}){const [busy,setBusy]=useState(false);async function upload(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files||[]).slice(0,20-logos.length);if(!files.length)return;setBusy(true);try{const uploaded:string[]=[];for(const file of files){const form=new FormData();form.append('file',await optimize(file));const response=await fetch('/api/upload?template=landing-contable',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error();uploaded.push(data.url)}onChange([...logos,...uploaded])}catch{alert('No se pudieron cargar todos los logos.')}finally{setBusy(false);event.target.value=''}}return <div className="client-logo-editor"><label><span>Logos de clientes</span><input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={upload}/><small>{busy?'Optimizando y subiendo…':'Puedes subir hasta 20 logos. La marquesina solo aparece cuando hay logos.'}</small></label><div>{logos.map((logo,index)=><figure key={`${logo}-${index}`}><img src={logo} alt={`Logo ${index+1}`}/><button type="button" onClick={()=>onChange(logos.filter((_,i)=>i!==index))}>Quitar</button></figure>)}</div></div>}
function LivePreview({content,target}:{content:AccountingLanding;target:string}){const frameRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLDivElement>(null),[scale,setScale]=useState(.45);useEffect(()=>{const frame=frameRef.current;if(!frame)return;const resize=()=>setScale(Math.min(frame.clientWidth/1440,frame.clientHeight/900));resize();const observer=new ResizeObserver(resize);observer.observe(frame);return()=>observer.disconnect()},[]);useEffect(()=>{const frame=frameRef.current,canvas=canvasRef.current;if(!frame||!canvas)return;const timer=requestAnimationFrame(()=>{const section=canvas.querySelector<HTMLElement>(target);if(!section)return;frame.scrollTo({top:Math.max(0,section.offsetTop*scale-12),behavior:'smooth'})});return()=>cancelAnimationFrame(timer)},[target,scale]);return <section className="landing-live-preview"><header><div><small>VISTA PREVIA EN VIVO</small><b>Se mueve hacia lo que estás editando</b></div><a href="/estudio-contable" target="_blank">Abrir ↗</a></header><div ref={frameRef} className="landing-preview-frame"><div ref={canvasRef} className="landing-preview-canvas" style={{transform:`scale(${scale})`}}><LandingView content={content} preview/></div></div></section>}

export default function AccountingLandingPage({admin=false}:{admin?:boolean}){const [content,setContent]=useState(defaultAccountingLanding),[loading,setLoading]=useState(admin),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[previewTarget,setPreviewTarget]=useState('#inicio');useEffect(()=>{fetch('/api/accounting-landing',{cache:'no-store'}).then(async response=>{if(admin&&response.status===401){location.replace('/login?next=%2Festudio-contable%2Fadmin');return}if(response.ok){const data=await response.json();setContent(normalizeAccountingLanding(data.content))}}).finally(()=>setLoading(false))},[admin]);if(!admin)return <LandingView content={content}/>;
 const set=<K extends keyof AccountingLanding>(key:K,value:AccountingLanding[K])=>setContent(current=>({...current,[key]:value}));const setItem=(key:'pillars'|'approachPoints'|'services'|'reasons',index:number,item:LandingItem)=>set(key,content[key].map((current,i)=>i===index?item:current) as AccountingLanding[typeof key]);async function save(){setSaving(true);setNotice('');const response=await fetch('/api/accounting-landing',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});if(response.status===401){location.replace('/login?next=%2Festudio-contable%2Fadmin');return}setNotice(response.ok?'Cambios publicados correctamente.':'No se pudo guardar. Intenta nuevamente.');setSaving(false)}
 if(loading)return <main className="landing-admin-loading">Abriendo editor…</main>;
 const syncPreview=(event:React.SyntheticEvent<HTMLElement>)=>{const block=(event.target as HTMLElement).closest<HTMLElement>('[data-preview-target]');if(block?.dataset.previewTarget)setPreviewTarget(block.dataset.previewTarget)};
 return <main className="landing-admin"><aside><a className="accounting-brand" href="/estudio-contable"><BrandLogo content={content}/></a><p>EDITOR DE LANDING</p><nav><a href="#edit-brand" onClick={()=>setPreviewTarget('#inicio')}>Marca y portada</a><a href="#edit-about" onClick={()=>setPreviewTarget('#nosotros')}>Nosotros</a><a href="#edit-services" onClick={()=>setPreviewTarget('#servicios')}>Servicios</a><a href="#edit-why" onClick={()=>setPreviewTarget('#beneficios')}>Beneficios</a><a href="#edit-logos" onClick={()=>setPreviewTarget('.client-marquee')}>Clientes</a><a href="#edit-contact" onClick={()=>setPreviewTarget('#contacto')}>Contacto</a></nav><a className="view-landing" href="/estudio-contable" target="_blank">Ver landing ↗</a></aside><section className="landing-editor" onFocusCapture={syncPreview} onPointerDownCapture={syncPreview}><header><div><small>ADMINISTRACIÓN</small><h1>Landing del estudio contable</h1></div><button onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar y publicar'}</button></header>{notice&&<div className="landing-save-notice">{notice}</div>}
 <section id="edit-brand" className="landing-editor-card" data-preview-target="#inicio"><h2>Marca y portada</h2><div className="landing-fields"><TextField label="Nombre del estudio" value={content.brand} onChange={v=>set('brand',v)}/><TextField label="WhatsApp" value={content.whatsapp} onChange={v=>set('whatsapp',v)}/><PhotoField label="Logo del estudio" value={content.logoImage} onChange={v=>set('logoImage',v)}/><TextField label="Aviso superior" value={content.topNotice} onChange={v=>set('topNotice',v)}/><TextField label="Texto del botón superior" value={content.brochureLabel} onChange={v=>set('brochureLabel',v)}/><TextField label="Etiqueta de portada" value={content.heroEyebrow} onChange={v=>set('heroEyebrow',v)}/><TextField label="Título principal" value={content.heroTitle} area onChange={v=>set('heroTitle',v)}/><label><span>Efecto del título</span><select value={content.heroTextEffect} onChange={e=>set('heroTextEffect',e.target.value==='dia'?'dia':'classic')}><option value="classic">Clásico blanco</option><option value="dia">Dia Reveal degradado</option></select></label><TextField label="Descripción principal" value={content.heroDescription} area onChange={v=>set('heroDescription',v)}/><TextField label="Texto del botón" value={content.heroButton} onChange={v=>set('heroButton',v)}/><PhotoField label="Foto de portada" value={content.heroImage} onChange={v=>set('heroImage',v)}/></div><h3>Beneficios dentro de la portada</h3><div className="landing-items">{content.pillars.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('pillars',index,v)}/>)}</div></section>
 <section id="edit-about" className="landing-editor-card" data-preview-target="#nosotros"><h2>Nosotros y enfoque</h2><div className="landing-fields"><TextField label="Título de nosotros" value={content.aboutTitle} onChange={v=>set('aboutTitle',v)}/><TextField label="Texto de nosotros" value={content.aboutText} area onChange={v=>set('aboutText',v)}/><TextField label="Años / cifra" value={content.experienceValue} onChange={v=>set('experienceValue',v)}/><TextField label="Texto de experiencia" value={content.experienceLabel} onChange={v=>set('experienceLabel',v)}/><PhotoField label="Foto de equipo" value={content.aboutImage} onChange={v=>set('aboutImage',v)}/><TextField label="Título del enfoque" value={content.approachTitle} onChange={v=>set('approachTitle',v)}/><TextField label="Texto del enfoque" value={content.approachText} area onChange={v=>set('approachText',v)}/><PhotoField label="Foto del enfoque" value={content.approachImage} onChange={v=>set('approachImage',v)}/></div><div className="landing-items">{content.approachPoints.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('approachPoints',index,v)}/>)}</div></section>
 <section id="edit-services" className="landing-editor-card" data-preview-target="#servicios"><h2>Servicios</h2><div className="landing-fields"><TextField label="Título" value={content.servicesTitle} onChange={v=>set('servicesTitle',v)}/><TextField label="Introducción" value={content.servicesIntro} area onChange={v=>set('servicesIntro',v)}/></div><div className="landing-items service-editors">{content.services.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('services',index,v)}/>)}</div></section>
 <section id="edit-why" className="landing-editor-card" data-preview-target="#beneficios"><h2>Beneficios y cierre</h2><div className="landing-fields"><TextField label="Título de beneficios" value={content.whyTitle} onChange={v=>set('whyTitle',v)}/><TextField label="Texto de beneficios" value={content.whyText} area onChange={v=>set('whyText',v)}/><PhotoField label="Foto de beneficios" value={content.whyImage} onChange={v=>set('whyImage',v)}/><TextField label="Título final" value={content.ctaTitle} onChange={v=>set('ctaTitle',v)}/><TextField label="Texto final" value={content.ctaText} area onChange={v=>set('ctaText',v)}/><TextField label="Botón final" value={content.ctaButton} onChange={v=>set('ctaButton',v)}/><PhotoField label="Foto del cierre" value={content.ctaImage} onChange={v=>set('ctaImage',v)}/></div><div className="landing-items">{content.reasons.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('reasons',index,v)}/>)}</div></section>
 <section id="edit-logos" className="landing-editor-card" data-preview-target=".client-marquee"><h2>Logos de clientes</h2><p className="landing-card-help">Estos logos se muestran sin tarjetas de fondo, en una marquesina continua antes del pie de página.</p><LogoEditor logos={content.clientLogos} onChange={v=>set('clientLogos',v)}/></section>
 <section id="edit-contact" className="landing-editor-card" data-preview-target="#contacto"><h2>Contacto</h2><div className="landing-fields"><TextField label="Dirección" value={content.address} onChange={v=>set('address',v)}/><TextField label="Teléfono" value={content.phone} onChange={v=>set('phone',v)}/><TextField label="Correo" value={content.email} onChange={v=>set('email',v)}/></div></section>
 </section><LivePreview content={content} target={previewTarget}/></main>}
