'use client';
import {useEffect,useState,type ChangeEvent} from 'react';
import {accountingIconKeys,defaultAccountingLanding,normalizeAccountingLanding,type AccountingLanding,type LandingItem} from '@/lib/accounting-landing';

const iconNames:Record<string,string>={ledger:'Documento',chart:'Gráfico',growth:'Crecimiento',shield:'Escudo',balance:'Balanza',people:'Equipo',briefcase:'Maletín',target:'Objetivo',folder:'Carpeta',calculator:'Calculadora',check:'Check',building:'Empresa'};

function Icon({name}:{name:string}){const common={fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};const paths:Record<string,React.ReactNode>={
 ledger:<><path {...common} d="M6 3h9l3 3v15H6z"/><path {...common} d="M15 3v4h4M9 11h6M9 15h6"/></>,
 chart:<><path {...common} d="M4 20V9M10 20V4M16 20v-7M22 20H2"/></>,
 growth:<><path {...common} d="m3 17 6-6 4 4 8-9"/><path {...common} d="M16 6h5v5"/></>,
 shield:<><path {...common} d="M12 3 4.5 6v5.5c0 4.7 3.1 7.8 7.5 9.5 4.4-1.7 7.5-4.8 7.5-9.5V6z"/><path {...common} d="m9 12 2 2 4-5"/></>,
 balance:<><path {...common} d="M12 3v18M5 6h14M7 6l-4 8h8zM17 6l-4 8h8z"/></>,
 people:<><path {...common} d="M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a4 4 0 1 0 0-8M18 8a3 3 0 0 1 0 6M22 20v-2a4 4 0 0 0-3-3.7"/></>,
 briefcase:<><path {...common} d="M4 7h16v13H4zM9 7V4h6v3M4 12h16M10 12v2h4v-2"/></>,
 target:<><circle {...common} cx="12" cy="12" r="9"/><circle {...common} cx="12" cy="12" r="5"/><circle {...common} cx="12" cy="12" r="1"/></>,
 folder:<><path {...common} d="M3 6h7l2 2h9v11H3z"/></>,
 calculator:<><rect {...common} x="5" y="2" width="14" height="20" rx="2"/><path {...common} d="M8 6h8v4H8zM8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01M16 18h.01"/></>,
 check:<><circle {...common} cx="12" cy="12" r="9"/><path {...common} d="m8 12 3 3 5-6"/></>,
 building:<><path {...common} d="M4 21V5l8-3 8 3v16M8 8h.01M12 8h.01M16 8h.01M8 12h.01M12 12h.01M16 12h.01M9 21v-5h6v5"/></>
};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]||paths.ledger}</svg>}

function wa(content:AccountingLanding,text:string){return `https://api.whatsapp.com/send?phone=${content.whatsapp.replace(/\D/g,'')}&text=${encodeURIComponent(text)}`}

export function LandingView({content,preview=false}:{content:AccountingLanding;preview?:boolean}){return <main className={`accounting-landing${preview?' is-preview':''}`}>
 <div className="accounting-notice"><span>{content.topNotice}</span><a href={wa(content,'Hola, deseo recibir información sobre sus servicios contables.')} target="_blank" rel="noreferrer">{content.brochureLabel} <b>→</b></a></div>
 <header className="accounting-nav"><a className="accounting-brand" href="#inicio"><i><Icon name="building"/></i><b>{content.brand}</b></a><nav><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#beneficios">Beneficios</a><a href="#contacto">Contacto</a></nav><a className="nav-cta" href={wa(content,'Hola, deseo agendar una consulta contable.')} target="_blank" rel="noreferrer">CONSULTA GRATIS</a>{!preview&&<a className="landing-admin-link" href="/estudio-contable/admin">Administrar</a>}</header>
 <section id="inicio" className="accounting-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(5,5,5,.97),rgba(78,0,4,.73) 55%,rgba(217,8,15,.16)),url(${content.heroImage})`}}><div><span>{content.heroEyebrow}</span><h1>{content.heroTitle}</h1><p>{content.heroDescription}</p><a href={wa(content,'Hola, deseo agendar una consulta para mi empresa.')} target="_blank" rel="noreferrer">{content.heroButton} <b>→</b></a></div></section>
 <section className="accounting-pillars">{content.pillars.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><b>{item.title}</b><span>{item.description}</span></div></article>)}</section>
 <section id="nosotros" className="accounting-split about-block"><div className="accounting-copy"><small>NOSOTROS</small><h2>{content.aboutTitle}</h2><p>{content.aboutText}</p><div className="experience"><strong>{content.experienceValue}</strong><span>{content.experienceLabel}</span></div></div><img src={content.aboutImage} alt="Equipo del estudio contable" loading="lazy"/></section>
 <section className="accounting-split approach-block"><img src={content.approachImage} alt="Asesoría empresarial" loading="lazy"/><div className="accounting-copy"><small>NUESTRA MIRADA</small><h2>{content.approachTitle}</h2><p>{content.approachText}</p><div className="approach-list">{content.approachPoints.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><b>{item.title}</b><span>{item.description}</span></div></article>)}</div></div></section>
 <section id="servicios" className="accounting-services"><div className="section-heading"><small>SERVICIOS</small><h2>{content.servicesTitle}</h2><p>{content.servicesIntro}</p></div><div>{content.services.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><h3>{item.title}</h3><p>{item.description}</p><a href={wa(content,`Hola, deseo información sobre ${item.title}.`)} target="_blank" rel="noreferrer">MÁS INFORMACIÓN <b>→</b></a></div></article>)}</div></section>
 <section id="beneficios" className="accounting-why"><div className="accounting-copy"><small>NUESTRO COMPROMISO</small><h2>{content.whyTitle}</h2><p>{content.whyText}</p><div className="reason-grid">{content.reasons.map((item,index)=><article key={index}><i><Icon name={item.icon}/></i><div><b>{item.title}</b><span>{item.description}</span></div></article>)}</div></div><img src={content.whyImage} alt="Consultoría contable personalizada" loading="lazy"/></section>
 <section className="accounting-cta" style={{backgroundImage:`linear-gradient(90deg,rgba(5,5,5,.96),rgba(132,0,7,.7)),url(${content.ctaImage})`}}><h2>{content.ctaTitle}</h2><p>{content.ctaText}</p><a href={wa(content,'Hola, deseo solicitar una asesoría contable.')} target="_blank" rel="noreferrer">{content.ctaButton} <b>→</b></a></section>
 <footer id="contacto" className="accounting-footer"><a className="accounting-brand" href="#inicio"><i><Icon name="building"/></i><b>{content.brand}</b></a><div><b>CONTACTO</b><span>{content.address}</span><a href={`tel:${content.phone.replace(/[^\d+]/g,'')}`}>{content.phone}</a><a href={`mailto:${content.email}`}>{content.email}</a></div><div><b>SERVICIOS</b>{content.services.slice(0,4).map((item,index)=><span key={index}>{item.title}</span>)}</div></footer>
 </main>}

async function optimize(file:File){if(!file.type.startsWith('image/'))return file;try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')?.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/webp',.82));return blob?new File([blob],file.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'}):file}catch{return file}}

function TextField({label,value,onChange,area=false}:{label:string;value:string;onChange:(value:string)=>void;area?:boolean}){return <label><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function PhotoField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){const [busy,setBusy]=useState(false);async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);try{const form=new FormData();form.append('file',await optimize(file));const response=await fetch('/api/upload?template=landing-contable',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error();onChange(data.url)}catch{alert('No se pudo cargar la imagen.')}finally{setBusy(false)}}return <label className="landing-photo-field"><span>{label}</span><img src={value} alt="Vista previa"/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/><small>{busy?'Optimizando y subiendo…':'JPG, PNG o WebP. Se optimiza automáticamente.'}</small></label>}
function ItemEditor({item,onChange}:{item:LandingItem;onChange:(item:LandingItem)=>void}){return <div className="landing-item-editor"><label><span>Icono</span><select value={item.icon} onChange={e=>onChange({...item,icon:e.target.value})}>{accountingIconKeys.map(key=><option key={key} value={key}>{iconNames[key]}</option>)}</select></label><TextField label="Título" value={item.title} onChange={title=>onChange({...item,title})}/><TextField label="Descripción" value={item.description} area onChange={description=>onChange({...item,description})}/></div>}

export default function AccountingLandingPage({admin=false}:{admin?:boolean}){const [content,setContent]=useState(defaultAccountingLanding),[loading,setLoading]=useState(admin),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');useEffect(()=>{fetch('/api/accounting-landing',{cache:'no-store'}).then(async response=>{if(admin&&response.status===401){location.replace('/login?next=%2Festudio-contable%2Fadmin');return}if(response.ok){const data=await response.json();setContent(normalizeAccountingLanding(data.content))}}).finally(()=>setLoading(false))},[admin]);if(!admin)return <LandingView content={content}/>;
 const set=<K extends keyof AccountingLanding>(key:K,value:AccountingLanding[K])=>setContent(current=>({...current,[key]:value}));const setItem=(key:'pillars'|'approachPoints'|'services'|'reasons',index:number,item:LandingItem)=>set(key,content[key].map((current,i)=>i===index?item:current) as AccountingLanding[typeof key]);async function save(){setSaving(true);setNotice('');const response=await fetch('/api/accounting-landing',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});if(response.status===401){location.replace('/login?next=%2Festudio-contable%2Fadmin');return}setNotice(response.ok?'Cambios publicados correctamente.':'No se pudo guardar. Intenta nuevamente.');setSaving(false)}
 if(loading)return <main className="landing-admin-loading">Abriendo editor…</main>;
 return <main className="landing-admin"><aside><a className="accounting-brand" href="/estudio-contable"><i><Icon name="building"/></i><b>{content.brand}</b></a><p>EDITOR DE LANDING</p><nav><a href="#edit-brand">Marca y portada</a><a href="#edit-about">Nosotros</a><a href="#edit-services">Servicios</a><a href="#edit-why">Beneficios</a><a href="#edit-contact">Contacto</a></nav><a className="view-landing" href="/estudio-contable" target="_blank">Ver landing ↗</a></aside><section className="landing-editor"><header><div><small>ADMINISTRACIÓN</small><h1>Landing del estudio contable</h1></div><button onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar y publicar'}</button></header>{notice&&<div className="landing-save-notice">{notice}</div>}
 <section id="edit-brand" className="landing-editor-card"><h2>Marca y portada</h2><div className="landing-fields"><TextField label="Nombre del estudio" value={content.brand} onChange={v=>set('brand',v)}/><TextField label="WhatsApp" value={content.whatsapp} onChange={v=>set('whatsapp',v)}/><TextField label="Aviso superior" value={content.topNotice} onChange={v=>set('topNotice',v)}/><TextField label="Texto del botón superior" value={content.brochureLabel} onChange={v=>set('brochureLabel',v)}/><TextField label="Etiqueta de portada" value={content.heroEyebrow} onChange={v=>set('heroEyebrow',v)}/><TextField label="Título principal" value={content.heroTitle} area onChange={v=>set('heroTitle',v)}/><TextField label="Descripción principal" value={content.heroDescription} area onChange={v=>set('heroDescription',v)}/><TextField label="Texto del botón" value={content.heroButton} onChange={v=>set('heroButton',v)}/><PhotoField label="Foto de portada" value={content.heroImage} onChange={v=>set('heroImage',v)}/></div><h3>Beneficios bajo la portada</h3><div className="landing-items">{content.pillars.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('pillars',index,v)}/>)}</div></section>
 <section id="edit-about" className="landing-editor-card"><h2>Nosotros y enfoque</h2><div className="landing-fields"><TextField label="Título de nosotros" value={content.aboutTitle} onChange={v=>set('aboutTitle',v)}/><TextField label="Texto de nosotros" value={content.aboutText} area onChange={v=>set('aboutText',v)}/><TextField label="Años / cifra" value={content.experienceValue} onChange={v=>set('experienceValue',v)}/><TextField label="Texto de experiencia" value={content.experienceLabel} onChange={v=>set('experienceLabel',v)}/><PhotoField label="Foto de equipo" value={content.aboutImage} onChange={v=>set('aboutImage',v)}/><TextField label="Título del enfoque" value={content.approachTitle} onChange={v=>set('approachTitle',v)}/><TextField label="Texto del enfoque" value={content.approachText} area onChange={v=>set('approachText',v)}/><PhotoField label="Foto del enfoque" value={content.approachImage} onChange={v=>set('approachImage',v)}/></div><div className="landing-items">{content.approachPoints.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('approachPoints',index,v)}/>)}</div></section>
 <section id="edit-services" className="landing-editor-card"><h2>Servicios</h2><div className="landing-fields"><TextField label="Título" value={content.servicesTitle} onChange={v=>set('servicesTitle',v)}/><TextField label="Introducción" value={content.servicesIntro} area onChange={v=>set('servicesIntro',v)}/></div><div className="landing-items service-editors">{content.services.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('services',index,v)}/>)}</div></section>
 <section id="edit-why" className="landing-editor-card"><h2>Beneficios y cierre</h2><div className="landing-fields"><TextField label="Título de beneficios" value={content.whyTitle} onChange={v=>set('whyTitle',v)}/><TextField label="Texto de beneficios" value={content.whyText} area onChange={v=>set('whyText',v)}/><PhotoField label="Foto de beneficios" value={content.whyImage} onChange={v=>set('whyImage',v)}/><TextField label="Título final" value={content.ctaTitle} onChange={v=>set('ctaTitle',v)}/><TextField label="Texto final" value={content.ctaText} area onChange={v=>set('ctaText',v)}/><TextField label="Botón final" value={content.ctaButton} onChange={v=>set('ctaButton',v)}/><PhotoField label="Foto del cierre" value={content.ctaImage} onChange={v=>set('ctaImage',v)}/></div><div className="landing-items">{content.reasons.map((item,index)=><ItemEditor key={index} item={item} onChange={v=>setItem('reasons',index,v)}/>)}</div></section>
 <section id="edit-contact" className="landing-editor-card"><h2>Contacto</h2><div className="landing-fields"><TextField label="Dirección" value={content.address} onChange={v=>set('address',v)}/><TextField label="Teléfono" value={content.phone} onChange={v=>set('phone',v)}/><TextField label="Correo" value={content.email} onChange={v=>set('email',v)}/></div></section>
 </section></main>}
