import { env } from 'cloudflare:workers';
import { authConfigured, privateError, SESSION_COOKIE, tenantFromHost } from '@/lib/admin-auth';
import { verifyPassword, randomSession, sessionDigest } from '@/lib/passwords';
export async function POST(request:Request){
 if(!authConfigured(env))return privateError(503,'admin_auth_not_configured');const url=new URL(request.url);if(url.protocol!=='https:'||request.headers.get('origin')!==url.origin)return privateError(403,'invalid_origin');
 const text=await request.text();if(text.length>4096)return privateError(413,'request_too_large');let body;try{body=JSON.parse(text)}catch{return privateError(400,'invalid_request')}
 const identifier=String(body.identifier||body.email||'').normalize('NFD').replace(/[̀-ͯ]/g,'').trim().toLowerCase().replace(/[^a-z0-9@._+-]+/g,'-').replace(/^-+|-+$/g,''),password=String(body.password||'');if(!identifier||identifier.length>254||password.length>128)return privateError(400,'invalid_request');
 const now=Date.now(),ip=request.headers.get('CF-Connecting-IP')||'unknown';for(const identity of ['ip:'+ip,'account:'+url.hostname+':'+identifier]){const key=sessionDigest(identity,env.AUTH_SECRET!);const row=await env.DB.prepare('INSERT INTO catalog_login_limits (key,count,resets_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN resets_at<=? THEN 1 ELSE count+1 END,resets_at=CASE WHEN resets_at<=? THEN excluded.resets_at ELSE resets_at END RETURNING count').bind(key,now+900000,now,now).first<{count:number}>();if(!row||row.count>(identity.startsWith('ip:')?30:8))return privateError(429,'too_many_attempts')}
 const owner=identifier===env.OWNER_EMAIL!.toLowerCase(),slug=tenantFromHost(url.hostname);const user=!owner&&slug?await env.DB.prepare('SELECT u.id,u.password_hash FROM catalog_admins u JOIN stores s ON s.id=u.store_id WHERE s.slug=? AND u.email=? AND u.active=1').bind(slug,identifier).first<{id:string;password_hash:string}>():null;const valid=await verifyPassword(password,owner?env.OWNER_PASSWORD_HASH!:user?.password_hash||env.OWNER_PASSWORD_HASH!);if(!valid||(!owner&&!user))return privateError(401,'invalid_credentials');
 const token=randomSession();await env.DB.batch([env.DB.prepare('DELETE FROM catalog_sessions WHERE expires_at<=?').bind(now),env.DB.prepare('DELETE FROM catalog_login_limits WHERE resets_at<=?').bind(now),env.DB.prepare('INSERT INTO catalog_sessions(token_hash,user_id,owner_email,owner_version,host,expires_at) VALUES (?,?,?,?,?,?)').bind(sessionDigest(token,env.AUTH_SECRET!),user?.id||null,owner?identifier:null,owner?sessionDigest(env.OWNER_PASSWORD_HASH!,env.AUTH_SECRET!):null,url.hostname,now+28800000)]);return Response.json({ok:true},{headers:{'Cache-Control':'no-store','Set-Cookie':SESSION_COOKIE+'='+token+'; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=28800'}})
}
