import { generatedBusinessTemplates } from './generated-business-catalogs';

export type TemplateKey='restaurantes'|'comida-rapida'|'detalles-romanticos'|'ropa'|'mujer'|'zapatos-mujer'|'perfumeria'|'postres'|'accesorios';
export type ProductOption={name:string;values:string[]};
export type TemplateProduct={id:number;name:string;category:string;description:string;price:number;oldPrice:number;image:string;active:boolean;options?:ProductOption[];whatsappMessage?:string};
export type TemplateStore={name:string;whatsapp:string;slug:string;accent:string;backgroundColor:string;backgroundImage:string;fontFamily:string;headingFont?:string;buttonColor?:string;secondaryColor?:string;textColor?:string;surfaceColor?:string;overlayStrength?:number;catalogTitle:string;logoUrl:string};
export const templates:Record<TemplateKey,{label:string;store:TemplateStore;products:TemplateProduct[]}>= {
 restaurantes:{label:'Restaurantes',store:{name:'MESA',whatsapp:'51999999999',slug:'',accent:'#d6a85f',backgroundColor:'#101814',backgroundImage:'',fontFamily:'Georgia',catalogTitle:'NUESTRA CARTA',logoUrl:''},products:[{id:101,name:'Lomo de la Casa',category:'FONDOS',description:'Lomo fino, papas doradas y salsa especial',price:42,oldPrice:0,image:'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=85',active:true},{id:102,name:'Pasta al Pesto',category:'PASTAS',description:'Pasta artesanal, pesto y queso parmesano',price:32,oldPrice:0,image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85',active:true},{id:103,name:'Ceviche Clásico',category:'MARINOS',description:'Pesca fresca, limón, camote y choclo',price:38,oldPrice:0,image:'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=900&q=85',active:true},{id:104,name:'Tiramisú',category:'POSTRES',description:'Café, mascarpone y cacao',price:18,oldPrice:0,image:'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=85',active:true}]},
 'comida-rapida':{label:'Comida rápida',store:{name:'CRUNCH',whatsapp:'51999999999',slug:'',accent:'#ffcf24',backgroundColor:'#180807',backgroundImage:'',fontFamily:'Trebuchet MS',catalogTitle:'ANTOJOS SIN ESPERA',logoUrl:''},products:[{id:201,name:'Burger Doble',category:'BURGERS',description:'Doble carne, cheddar, tocino y salsa Crunch',price:24.9,oldPrice:29.9,image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',active:true},{id:202,name:'Pizza Pepperoni',category:'PIZZAS',description:'Masa artesanal, mozzarella y pepperoni',price:34.9,oldPrice:39.9,image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85',active:true},{id:203,name:'Alitas BBQ',category:'COMBOS',description:'8 alitas, papas y bebida',price:27.9,oldPrice:32.9,image:'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=900&q=85',active:true},{id:204,name:'Papas Supreme',category:'PIQUEOS',description:'Papas, cheddar, tocino y cebolla crocante',price:18.9,oldPrice:22.9,image:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',active:true}]},
 ropa:{label:'Ropa',store:{name:'NOVA',whatsapp:'51999999999',slug:'',accent:'#8fa7ff',backgroundColor:'#08090d',backgroundImage:'',fontFamily:'Inter',catalogTitle:'NUEVA COLECCIÓN',logoUrl:''},products:[
  {id:301,name:'Polo Azul Marino',category:'POLOS',description:'Algodón piqué premium · Cuello reforzado',price:69,oldPrice:89,image:'https://images.unsplash.com/photo-1627225924765-552d49cf47ad?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Azul marino']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir el {producto} en color azul marino.\n{opciones}\nPrecio: S/ {precio}'},
  {id:302,name:'Polo Blanco Essential',category:'POLOS',description:'Algodón suave · Corte clásico',price:65,oldPrice:82,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Blanco']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir el {producto} en color blanco.\n{opciones}\nPrecio: S/ {precio}'},
  {id:303,name:'Polo Negro Urban',category:'POLOS',description:'Jersey de algodón · Fit moderno',price:65,oldPrice:82,image:'https://images.unsplash.com/photo-1583743814966-8936f37f4678?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Negro']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir el {producto} en color negro.\n{opciones}\nPrecio: S/ {precio}'},
  {id:304,name:'Polo Verde Olivo',category:'POLOS',description:'Algodón respirable · Acabado lavado',price:69,oldPrice:89,image:'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Verde olivo']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir el {producto} en color verde olivo.\n{opciones}\nPrecio: S/ {precio}'},
  {id:305,name:'Polo Rojo Statement',category:'POLOS',description:'Algodón peinado · Color intenso',price:69,oldPrice:89,image:'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Rojo']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir el {producto} en color rojo.\n{opciones}\nPrecio: S/ {precio}'},
  {id:306,name:'Jean Azul Relaxed',category:'PANTALONES',description:'Denim resistente · Corte relajado',price:109,oldPrice:139,image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Azul denim']},{name:'Talla',values:['28','30','32','34','36']}],whatsappMessage:'Hola, quiero pedir el {producto} azul denim.\n{opciones}\nPrecio: S/ {precio}'},
  {id:307,name:'Cargo Negro Utility',category:'PANTALONES',description:'Bolsillos laterales · Fit urbano',price:119,oldPrice:149,image:'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Negro']},{name:'Talla',values:['28','30','32','34','36']}],whatsappMessage:'Hola, quiero pedir el {producto} en negro.\n{opciones}\nPrecio: S/ {precio}'},
  {id:308,name:'Chino Beige Classic',category:'PANTALONES',description:'Gabardina stretch · Corte recto',price:99,oldPrice:129,image:'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Beige']},{name:'Talla',values:['28','30','32','34','36']}],whatsappMessage:'Hola, quiero pedir el {producto} en beige.\n{opciones}\nPrecio: S/ {precio}'},
  {id:309,name:'Jogger Gris Motion',category:'PANTALONES',description:'Felpa ligera · Pretina ajustable',price:89,oldPrice:115,image:'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Gris']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir el {producto} en gris.\n{opciones}\nPrecio: S/ {precio}'},
  {id:310,name:'Polera Negra Core',category:'POLERAS',description:'Felpa perchada · Capucha regulable',price:119,oldPrice:149,image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Negro']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir la {producto} en negro.\n{opciones}\nPrecio: S/ {precio}'},
  {id:311,name:'Polera Gris Cloud',category:'POLERAS',description:'Interior suave · Bolsillo canguro',price:115,oldPrice:145,image:'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Gris']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir la {producto} en gris.\n{opciones}\nPrecio: S/ {precio}'},
  {id:312,name:'Polera Beige Sand',category:'POLERAS',description:'Felpa premium · Estilo minimalista',price:125,oldPrice:159,image:'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Beige']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir la {producto} en beige.\n{opciones}\nPrecio: S/ {precio}'},
  {id:313,name:'Polera Azul Night',category:'POLERAS',description:'Algodón grueso · Corte oversized',price:129,oldPrice:165,image:'https://images.unsplash.com/photo-1609873814058-a8928924184a?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Azul noche']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir la {producto} en azul noche.\n{opciones}\nPrecio: S/ {precio}'},
  {id:314,name:'Polera Verde Forest',category:'POLERAS',description:'Felpa térmica · Puños reforzados',price:125,oldPrice:159,image:'https://images.unsplash.com/photo-1611911813383-67769b37a149?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Verde bosque']},{name:'Talla',values:['S','M','L','XL']}],whatsappMessage:'Hola, quiero pedir la {producto} en verde bosque.\n{opciones}\nPrecio: S/ {precio}'}
 ]},
 mujer:{label:'Moda para mujer',store:{name:'LUMÉ',whatsapp:'51999999999',slug:'',accent:'#ff74a6',backgroundColor:'#24131b',backgroundImage:'',fontFamily:'Georgia',catalogTitle:'HECHO PARA TI',logoUrl:''},products:[{id:401,name:'Vestido Amélie',category:'VESTIDOS',description:'Tallas XS–L · Caída ligera',price:129,oldPrice:159,image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85',active:true},{id:402,name:'Blazer Rose',category:'BLAZERS',description:'Tallas S–L · Corte estructurado',price:149,oldPrice:189,image:'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=900&q=85',active:true},{id:403,name:'Top Satin',category:'TOPS',description:'Tallas XS–L · Acabado satinado',price:69,oldPrice:89,image:'https://images.unsplash.com/photo-1564257577054-5f8bc7948be8?auto=format&fit=crop&w=900&q=85',active:true},{id:404,name:'Bolso Mini',category:'COMPLEMENTOS',description:'Correa regulable · Tres colores',price:89,oldPrice:119,image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85',active:true}]},
 'zapatos-mujer':{label:'Zapatos de mujer',store:{name:'LUNA SHOES',whatsapp:'51999999999',slug:'',accent:'#ff6fae',backgroundColor:'#1d1018',backgroundImage:'',fontFamily:'Inter',catalogTitle:'ZAPATOS QUE ELEVAN TU LOOK',logoUrl:''},products:[
  {id:601,name:'Tacón Rosa Gala',category:'TACONES',description:'Altura cómoda · Acabado satinado · Look elegante',price:129,oldPrice:169,image:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Rosa','Nude','Negro']},{name:'Talla',values:['35','36','37','38','39']}],whatsappMessage:'Hola, quiero pedir {producto}.\n{opciones}\nPrecio: S/ {precio}'},
  {id:602,name:'Stiletto Negro Noche',category:'TACONES',description:'Punta fina · Plantilla suave · Fiesta y oficina',price:139,oldPrice:179,image:'https://images.unsplash.com/photo-1554238113-6d3dbed5cf55?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Negro','Rojo vino','Beige']},{name:'Talla',values:['35','36','37','38','39','40']}],whatsappMessage:'Hola, quiero pedir {producto}.\n{opciones}\nPrecio: S/ {precio}'},
  {id:603,name:'Sandalia Dorada Glow',category:'SANDALIAS',description:'Tiras delicadas · Brillo sutil · Verano premium',price:89,oldPrice:119,image:'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Dorado','Plateado','Champagne']},{name:'Talla',values:['35','36','37','38','39']}],whatsappMessage:'Hola, quiero pedir {producto}.\n{opciones}\nPrecio: S/ {precio}'},
  {id:604,name:'Sneaker Blanco Chic',category:'ZAPATILLAS',description:'Casual elegante · Suela ligera · Uso diario',price:119,oldPrice:149,image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Blanco','Rosa pastel','Negro']},{name:'Talla',values:['35','36','37','38','39','40']}],whatsappMessage:'Hola, quiero pedir {producto}.\n{opciones}\nPrecio: S/ {precio}'},
  {id:605,name:'Botín Camel Urban',category:'BOTINES',description:'Cuero sintético · Tacón medio · Temporada urbana',price:159,oldPrice:199,image:'https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Camel','Negro','Chocolate']},{name:'Talla',values:['35','36','37','38','39']}],whatsappMessage:'Hola, quiero pedir {producto}.\n{opciones}\nPrecio: S/ {precio}'},
  {id:606,name:'Mule Beige Soft',category:'MULES',description:'Diseño abierto · Interior acolchado · Minimal premium',price:99,oldPrice:129,image:'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?auto=format&fit=crop&w=900&q=85',active:true,options:[{name:'Color',values:['Beige','Blanco','Rosa']},{name:'Talla',values:['35','36','37','38','39']}],whatsappMessage:'Hola, quiero pedir {producto}.\n{opciones}\nPrecio: S/ {precio}'}
 ]},
 accesorios:{label:'Accesorios',store:{name:'DETALLE',whatsapp:'51999999999',slug:'',accent:'#ff74a6',backgroundColor:'#25131c',backgroundImage:'',fontFamily:'Georgia',catalogTitle:'DETALLES QUE ENAMORAN',logoUrl:''},products:[{id:501,name:'Reloj Heritage',category:'RELOJES',description:'Acero inoxidable · Resistente al agua',price:189,oldPrice:239,image:'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=85',active:true},{id:502,name:'Collar Aura',category:'JOYERÍA',description:'Baño de oro · Largo regulable',price:79,oldPrice:99,image:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=85',active:true},{id:503,name:'Lentes Soho',category:'LENTES',description:'Protección UV400 · Estuche incluido',price:69,oldPrice:89,image:'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=85',active:true},{id:504,name:'Bolso Siena',category:'BOLSOS',description:'Correa regulable · Interior forrado',price:119,oldPrice:149,image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=85',active:true}]},
 ...generatedBusinessTemplates
};

