'use client';
import {useState} from 'react';
import './demo-sites.css';

const demos=[
 {id:'abogados',label:'Abogados',brand:'LEXA',brandLine:'ABOGADOS & CONSULTORES',tag:'DEFENSA LEGAL ESTRATÉGICA',title:'Protegemos tus decisiones y tu futuro.',copy:'Asesoría legal clara, confidencial y orientada a resultados para personas y empresas.',cta:'SOLICITAR CONSULTA',image:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1800&q=82',aboutImage:'https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=1200&q=82',accent:'#c7a35a',dark:'#11100e',aboutTitle:'Experiencia legal que inspira confianza.',about:'Analizamos cada caso con rigor, hablamos contigo con claridad y diseñamos una estrategia enfocada en proteger tus intereses.',cards:[['⚖','Derecho empresarial','Contratos, sociedades y prevención legal.'],['§','Defensa especializada','Estrategia sólida para cada caso.'],['✓','Consulta confidencial','Atención directa y absoluta reserva.']],clients:['GRUPO ATLAS','NOVA INDUSTRIAS','ANDES CORP','INTEGRA','PACÍFICO GROUP']},
 {id:'odontologia',label:'Odontología',brand:'ALBA',brandLine:'CLÍNICA DENTAL',tag:'SONRISAS QUE INSPIRAN CONFIANZA',title:'Tu mejor sonrisa empieza hoy.',copy:'Odontología integral con tecnología moderna, especialistas y citas rápidas por WhatsApp.',cta:'RESERVAR MI CITA',image:'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1800&q=82',aboutImage:'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1200&q=82',accent:'#37c7d6',dark:'#062a34',aboutTitle:'Cuidamos tu sonrisa con precisión y calidez.',about:'Un equipo especializado, diagnóstico digital y tratamientos personalizados para que vuelvas a sonreír con tranquilidad.',cards:[['✦','Diseño de sonrisa','Tratamientos personalizados y naturales.'],['◉','Implantes dentales','Recupera función, seguridad y bienestar.'],['♡','Odontología familiar','Cuidado amable para todas las edades.']],clients:['DENTA LAB','ORALTECH','MEDIDENT','SONRÍE PERÚ','CLÍNICA ALBA']},
 {id:'inmobiliaria',label:'Inmobiliarias',brand:'NÓRDICA',brandLine:'DESARROLLO INMOBILIARIO',tag:'INVIERTE EN TU PRÓXIMO CAPÍTULO',title:'Espacios para vivir y crecer.',copy:'Proyectos, lotes y departamentos seleccionados para ayudarte a tomar una gran decisión.',cta:'VER PROPIEDADES',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=82',aboutImage:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=82',accent:'#d7b878',dark:'#15211d',aboutTitle:'Encontramos el lugar que imaginas.',about:'Seleccionamos proyectos con ubicación, proyección y respaldo. Te acompañamos desde la primera visita hasta la entrega.',cards:[['⌂','Departamentos','Ubicaciones estratégicas y acabados premium.'],['◇','Lotes','Invierte hoy en zonas de alto crecimiento.'],['↗','Asesoría inmobiliaria','Acompañamiento desde la visita hasta la firma.']],clients:['URBANIA','VÉRTICE','HÁBITAT','LIMA NORTE','CAPITAL HOME']},
 {id:'academias',label:'Academias y colegios',brand:'AVANZA',brandLine:'COLEGIO & ACADEMIA',tag:'EDUCACIÓN QUE ABRE CAMINOS',title:'El futuro comienza aprendiendo.',copy:'Una comunidad educativa cercana, innovadora y preparada para desarrollar todo el potencial de cada estudiante.',cta:'INFORMES Y MATRÍCULAS',image:'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1800&q=82',aboutImage:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=82',accent:'#ffcc4d',dark:'#10254b',aboutTitle:'Formamos personas listas para transformar el mundo.',about:'Combinamos excelencia académica, valores y acompañamiento personalizado en un entorno donde cada estudiante puede crecer.',cards:[['★','Metodología moderna','Aprendizaje activo y acompañamiento constante.'],['◎','Docentes preparados','Experiencia, vocación y formación continua.'],['→','Matrículas abiertas','Conoce vacantes, horarios y modalidades.']],clients:['CAMBRIDGE','EDUCA LAB','LECTURA VIVA','STEM PERÚ','DEPORTE ESCOLAR']},
 {id:'contable',label:'Estudio contable',brand:'NEXO',brandLine:'ESTUDIO CONTABLE',tag:'DECISIONES CON INFORMACIÓN CLARA',title:'Convierte tus números en crecimiento.',copy:'Contabilidad, tributación y asesoría empresarial para negocios que quieren avanzar con seguridad.',cta:'AGENDAR ASESORÍA',image:'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1800&q=82',aboutImage:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=82',accent:'#ef233c',dark:'#090d17',aboutTitle:'Claridad contable para decisiones sólidas.',about:'Ordenamos tu información, reducimos riesgos y convertimos los números en una herramienta para dirigir mejor tu empresa.',cards:[['▥','Outsourcing contable','Control y reportes siempre actualizados.'],['↗','Planeamiento financiero','Decisiones basadas en información real.'],['✓','Asesoría tributaria','Cumplimiento y prevención de contingencias.']],clients:['GRUPO CRECE','FINANZA PRO','EMPRESA 360','NORTE SAC','INNOVA PYME']}
] as const;

export default function DemoSitios(){const [active,setActive]=useState(0),demo=demos[active];return <main key={demo.id} className="business-demo" style={{'--accent':demo.accent,'--dark':demo.dark} as React.CSSProperties}>
 <nav className="demo-rubros" aria-label="Cambiar demo"><a className="demo-platform" href="https://sitioweb.shop"><i>S</i><b>SITIOWEB.SHOP</b></a><small>CAMBIAR RUBRO</small><div>{demos.map((item,index)=><button key={item.id} className={index===active?'active':''} onClick={()=>setActive(index)}>{item.label}</button>)}</div><label><span>Cambiar rubro</span><select value={active} onChange={event=>setActive(Number(event.target.value))}>{demos.map((item,index)=><option value={index} key={item.id}>{item.label}</option>)}</select></label></nav>
 <header className="company-nav"><a className="company-brand" href="#inicio"><i>{demo.brand.slice(0,1)}</i><span><strong>{demo.brand}</strong><small>{demo.brandLine}</small></span></a><nav><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#contacto">Contacto</a></nav><a className="company-cta" href="https://wa.me/51999999999" target="_blank" rel="noreferrer">CONTÁCTANOS</a></header>
 <section id="inicio" className="demo-hero" style={{backgroundImage:`linear-gradient(90deg,${demo.dark}fa 0%,${demo.dark}d8 48%,${demo.dark}32 82%),url(${demo.image})`}}><div><small>{demo.tag}</small><h1>{demo.title}</h1><p>{demo.copy}</p><a href="https://wa.me/51999999999" target="_blank" rel="noreferrer">{demo.cta} <b>→</b></a></div></section>
 <section id="servicios" className="demo-cards">{demo.cards.map(card=><article key={card[1]}><i>{card[0]}</i><div><h2>{card[1]}</h2><p>{card[2]}</p></div></article>)}</section>
 <section id="nosotros" className="demo-company-about"><div><small>NOSOTROS</small><h2>{demo.aboutTitle}</h2><p>{demo.about}</p><ul><li>Atención personalizada</li><li>Especialistas con experiencia</li><li>Respuesta rápida por WhatsApp</li></ul><a href="https://wa.me/51999999999" target="_blank" rel="noreferrer">CONVERSEMOS <b>→</b></a></div><img src={demo.aboutImage} alt={`Equipo de ${demo.brand}`} loading="lazy"/></section>
 <section className="demo-benefits"><small>UNA EXPERIENCIA PROFESIONAL DE PRINCIPIO A FIN</small><h2>Confianza, cercanía y resultados.</h2><div><article><b>01</b><span>Escuchamos tu necesidad</span></article><article><b>02</b><span>Diseñamos la mejor solución</span></article><article><b>03</b><span>Te acompañamos en cada paso</span></article></div></section>
 <section className="demo-client-marquee"><p>EMPRESAS Y ALIADOS QUE CONFÍAN EN NOSOTROS</p><div><div>{[...demo.clients,...demo.clients].map((client,index)=><span key={`${client}-${index}`}>{client}</span>)}</div></div></section>
 <section className="demo-final-cta" style={{backgroundImage:`linear-gradient(90deg,${demo.dark}f5,${demo.dark}a8),url(${demo.image})`}}><small>ESTAMOS LISTOS PARA AYUDARTE</small><h2>Da el siguiente paso con confianza.</h2><p>{demo.copy}</p><a href="https://wa.me/51999999999" target="_blank" rel="noreferrer">{demo.cta} <b>→</b></a></section>
 <footer id="contacto"><a className="company-brand" href="#inicio"><i>{demo.brand.slice(0,1)}</i><span><strong>{demo.brand}</strong><small>{demo.brandLine}</small></span></a><div><b>CONTACTO</b><span>Av. Principal 123 · Lima, Perú</span><a href="tel:+51999999999">(+51) 999 999 999</a><a href={`mailto:contacto@${demo.brand.toLowerCase()}.pe`}>contacto@{demo.brand.toLowerCase()}.pe</a></div><div><b>ENLACES</b><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="https://wa.me/51999999999">WhatsApp</a></div><small>© 2026 {demo.brand}. Todos los derechos reservados.</small></footer>
 </main>}
