'use client';
import {useEffect,useRef,useState} from 'react';
import {defaultDemoSites,normalizeDemoSites} from '@/lib/demo-sites';
import './demo-sites.css';

const lawyerSlides=[
 {eyebrow:'ESTUDIO JURÍDICO ESPECIALIZADO',title:'El mejor equipo legal a tu disposición',copy:'Una firma con alta especialización y experiencia en la defensa de personas y empresas.',image:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1800&q=82'},
 {eyebrow:'FIRMA LEGAL RECONOCIDA',title:'Reconocida por el directorio internacional The Legal 500',copy:'Dispute Resolution: White Collar Crime.',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=82'},
 {eyebrow:'EXPERIENCIA COMPROBADA',title:'Firma altamente recomendada',copy:'Estrategia, rigurosidad y atención directa para cada patrocinio.',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=82'},
 {eyebrow:'EXCELENCIA Y RESPALDO',title:'Reconocida entre las firmas líderes',copy:'Soluciones legales especializadas para retos de alta complejidad.',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=82'}
];

export default function DemoSitios(){const [content,setContent]=useState(defaultDemoSites),[active,setActive]=useState(0),[lawyerSlide,setLawyerSlide]=useState(0),mainRef=useRef<HTMLElement>(null),demos=content.demos,demo=demos[active]||demos[0],slide=lawyerSlides[lawyerSlide];useEffect(()=>{fetch('/api/demo-sites',{cache:'no-store'}).then(async response=>{if(response.ok)setContent(normalizeDemoSites((await response.json()).content))}).catch(()=>{})},[]);useEffect(()=>{if(active!==0)return;const timer=window.setInterval(()=>setLawyerSlide(current=>(current+1)%lawyerSlides.length),5600);return()=>window.clearInterval(timer)},[active]);useEffect(()=>{if(active!==0||!mainRef.current||!('IntersectionObserver' in window))return;const elements=Array.from(mainRef.current.querySelectorAll<HTMLElement>('.lawyer-areas article,.lawyer-heading,.lawyer-stats article,.demo-company-about>div,.demo-company-about>img,.lawyer-purpose article,.lawyer-news article,.demo-final-cta>*'));elements.forEach(element=>element.classList.add('law-reveal'));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('law-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -40px'});elements.forEach(element=>observer.observe(element));return()=>observer.disconnect()},[active,content]);const wa=`https://wa.me/${demo.whatsapp.replace(/\D/g,'')}`;return <main ref={mainRef} key={demo.id} className={`business-demo${active===0?' lawyer-demo':''}`} style={{'--accent':demo.accent,'--dark':demo.dark} as React.CSSProperties}>
 <nav className="demo-rubros" aria-label="Cambiar demo"><a className="demo-platform" href="https://sitioweb.shop"><i>S</i><b>SITIOWEB.SHOP</b></a><small>CAMBIAR RUBRO</small><div>{demos.map((item,index)=><button key={item.id} className={index===active?'active':''} onClick={()=>setActive(index)}>{item.label}</button>)}</div><label><span>Cambiar rubro</span><select value={active} onChange={event=>setActive(Number(event.target.value))}>{demos.map((item,index)=><option value={index} key={item.id}>{item.label}</option>)}</select></label><a className="demo-admin" href="/admin">Administrar</a></nav>
 <header className="company-nav"><a className="company-brand" href="#inicio"><i>{demo.brand.slice(0,1)}</i><span><strong>{demo.brand}</strong><small>{demo.brandLine}</small></span></a><nav><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#contacto">Contacto</a></nav><a className="company-cta" href={wa} target="_blank" rel="noreferrer">CONTÁCTANOS</a></header>
 {active===0?<section key={lawyerSlide} id="inicio" className="demo-hero lawyer-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(30,39,45,.72),rgba(30,39,45,.12)),url(${lawyerSlide===0?demo.image:slide.image})`}}><button className="lawyer-arrow prev" aria-label="Diapositiva anterior" onClick={()=>setLawyerSlide(current=>(current+lawyerSlides.length-1)%lawyerSlides.length)}>‹</button><div><small>{lawyerSlide===0?demo.tag:slide.eyebrow}</small><h1>{lawyerSlide===0?demo.title:slide.title}</h1><p>{lawyerSlide===0?demo.copy:slide.copy}</p><a href="#servicios">{demo.cta} <b>→</b></a></div><button className="lawyer-arrow next" aria-label="Diapositiva siguiente" onClick={()=>setLawyerSlide(current=>(current+1)%lawyerSlides.length)}>›</button><div className="lawyer-dots">{lawyerSlides.map((_,index)=><button key={index} className={index===lawyerSlide?'active':''} aria-label={`Ir a diapositiva ${index+1}`} onClick={()=>setLawyerSlide(index)}/>)}</div></section>:<section id="inicio" className="demo-hero" style={{backgroundImage:`linear-gradient(90deg,${demo.dark}fa 0%,${demo.dark}d8 48%,${demo.dark}32 82%),url(${demo.image})`}}><div><small>{demo.tag}</small><h1>{demo.title}</h1><p>{demo.copy}</p><a href={wa} target="_blank" rel="noreferrer">{demo.cta} <b>→</b></a></div></section>}
 {active===0?<section id="servicios" className="lawyer-areas"><div className="lawyer-heading"><small>ESPECIALISTAS EN CADA ÁREA LEGAL</small><h2>Nuestras Áreas</h2><p>Soluciones jurídicas especializadas con una mirada estratégica y multidisciplinaria.</p></div><div>{content.legalAreas.map((area,index)=><article key={area[0]}><span>{String(index+1).padStart(2,'0')}</span><h3>{area[0]}</h3><p>{area[1]}</p><a href={wa}>Ver detalle →</a></article>)}</div></section>:<section id="servicios" className="demo-cards">{demo.cards.map(card=><article key={card[1]}><i>{card[0]}</i><div><h2>{card[1]}</h2><p>{card[2]}</p></div></article>)}</section>}
 {active===0&&<section className="lawyer-stats"><small>SOMOS EXPERTOS EN LO QUE HACEMOS</small><h2>Experiencia comprobada</h2><div><article><strong>90<sup>%</sup></strong><span>Casos de éxito</span></article><article><strong>20<sup>+</sup></strong><span>Años de experiencia</span></article><article><strong>92<sup>%</sup></strong><span>Índice de confianza</span></article><article><strong>50<sup>%</sup></strong><span>Crecimiento anual</span></article></div></section>}
 <section id="nosotros" className="demo-company-about"><div><small>NOSOTROS</small><h2>{demo.aboutTitle}</h2><p>{demo.about}</p><ul><li>Atención personalizada</li><li>Especialistas con experiencia</li><li>Respuesta rápida por WhatsApp</li></ul><a href={wa} target="_blank" rel="noreferrer">CONVERSEMOS <b>→</b></a></div><img src={demo.aboutImage} alt={`Equipo de ${demo.brand}`} loading="lazy"/></section>
 {active===0&&<section className="lawyer-purpose"><article><small>NUESTRA MISIÓN</small><h2>Servicio jurídico de excelencia.</h2><p>Nos comprometemos con cada caso y diseñamos soluciones efectivas para alcanzar los objetivos de cada patrocinio.</p></article><article><small>NUESTRA VISIÓN</small><h2>Disciplina, creatividad y rigor.</h2><p>Ejercemos una defensa legal de alta calidad, combinando especialización académica con experiencia profesional.</p></article></section>}
 <section className="demo-benefits"><small>UNA EXPERIENCIA PROFESIONAL DE PRINCIPIO A FIN</small><h2>Confianza, cercanía y resultados.</h2><div><article><b>01</b><span>Escuchamos tu necesidad</span></article><article><b>02</b><span>Diseñamos la mejor solución</span></article><article><b>03</b><span>Te acompañamos en cada paso</span></article></div></section>
 <section className="demo-client-marquee"><p>EMPRESAS Y ALIADOS QUE CONFÍAN EN NOSOTROS</p><div><div>{[...demo.clients,...demo.clients].map((client,index)=><span key={`${client}-${index}`}>{client}</span>)}</div></div></section>
 {active===0&&<section className="lawyer-news"><div className="lawyer-heading"><small>TE MANTENEMOS INFORMADO</small><h2>Nuestras Noticias</h2></div><div><article><span>JURISPRUDENCIA</span><h3>Actualidad penal y criterios relevantes para empresas</h3><a href={wa}>Solicitar información →</a></article><article><span>ANÁLISIS LEGAL</span><h3>Prevención de riesgos y cumplimiento corporativo</h3><a href={wa}>Solicitar información →</a></article><article><span>EVENTOS</span><h3>Capacitaciones y novedades para el sector empresarial</h3><a href={wa}>Solicitar información →</a></article></div></section>}
 <section className="demo-final-cta" style={{backgroundImage:`linear-gradient(90deg,${demo.dark}f5,${demo.dark}a8),url(${demo.image})`}}><small>ESTAMOS LISTOS PARA AYUDARTE</small><h2>Da el siguiente paso con confianza.</h2><p>{demo.copy}</p><a href={wa} target="_blank" rel="noreferrer">{demo.cta} <b>→</b></a></section>
 <footer id="contacto"><a className="company-brand" href="#inicio"><i>{demo.brand.slice(0,1)}</i><span><strong>{demo.brand}</strong><small>{demo.brandLine}</small></span></a><div><b>CONTACTO</b><span>{demo.address}</span><a href={`tel:${demo.phone.replace(/[^\d+]/g,'')}`}>{demo.phone}</a><a href={`mailto:${demo.email}`}>{demo.email}</a></div><div><b>ENLACES</b><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href={wa}>WhatsApp</a></div><small>© 2026 {demo.brand}. Todos los derechos reservados.</small></footer>
 </main>}
